    - name: Install all required dependencies
      apt: 
        name: 
           - python
           - python-setuptools
           - python-dev
           - build-essential
           - python-pip 
           - python-mysqldb
        state: present 
        force_apt_get: yes
